In [1]:
import numpy as np
import time
list = [[56.2,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]]
list1 = []
for i in range(0,len(list),1):
  a = []
  for j in range(0,len(list[i]),1):
    sum=0.0
    for k in range(0,len(list),1):
      sum=sum+list[k][j]
  
    a.append((list[i][j]/(sum))*100)
  
  list1.append(a)

print("By loop -> " , np.array(list1) , "\n", "process time= ", time.process_time())

arr = np.array(list)
print("By numpy -> " , arr / arr.sum(axis=0)*100, "\n", "process time= ", time.process_time())

By loop ->  [[94.93243243  0.          2.83140283 88.42652796]
 [ 2.02702703 43.51464435 33.46203346 10.40312094]
 [ 3.04054054 56.48535565 63.70656371  1.17035111]] 
 process time=  1.288832
By numpy ->  [[94.93243243  0.          2.83140283 88.42652796]
 [ 2.02702703 43.51464435 33.46203346 10.40312094]
 [ 3.04054054 56.48535565 63.70656371  1.17035111]] 
 process time=  1.289546
