In [56]:
import numpy as np
# food = [Apples, Beefs, Eggs, Potatoes]
Carb =   [56.0, 0.0, 4.4, 68.0]
Protein =[1.2, 104.0, 52.0, 8.0]
Fat =    [1.8, 135.0, 99.0, 0.9]

a =np.array(Carb)
b =np.array(Protein)
c =np.array(Fat)

array=np.vstack([a,b,c])
array


array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [55]:
array2=np.sum(array, axis=0)


array([ 59. , 239. , 155.4,  76.9])

In [60]:
array3=array2 / a.(range i for -1)
array3

SyntaxError: invalid syntax (<ipython-input-60-72d17a9eda0a>, line 1)

In [2]:
import numpy as np
import time
list = [[56.2,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]]
list1 = []
for i in range(0,len(list),1):
  a = []
  for j in range(0,len(list[i]),1):
    sum=0.0
    for k in range(0,len(list),1):
      sum=sum+list[k][j]
  
    a.append((list[i][j]/(sum))*100)
  
  list1.append(a)

print("By loop -> " , np.array(list1) , "\n", "process time= ", time.process_time())

arr = np.array(list)
print("By numpy -> " , arr / arr.sum(axis=0)*100, "\n", "process time= ", time.process_time())

By loop ->  [[94.93243243  0.          2.83140283 88.42652796]
 [ 2.02702703 43.51464435 33.46203346 10.40312094]
 [ 3.04054054 56.48535565 63.70656371  1.17035111]] 
 process time=  1.355835
By numpy ->  [[94.93243243  0.          2.83140283 88.42652796]
 [ 2.02702703 43.51464435 33.46203346 10.40312094]
 [ 3.04054054 56.48535565 63.70656371  1.17035111]] 
 process time=  1.356589
